# .github/workflows/changelog.yml

name: Changelog

on: push

jobs:
  release:
    name: Changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Changelog
        if: startsWith(github.ref, 'refs/tags/')
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
